[project]
name = "slcm"
description = "Student Life Cycle Management"
requires-python = ">=3.10,<3.15"
readme = "README.md"
dynamic = ["version"]

authors = [
    { name = "Nishanth", email = "nishanth.a@azimpremjifoundation.org" },
    { name = "TFSS", email = "tech4socialsector@azimpremjifoundation.org" }
]

dependencies = [
    "qrcode[pil]>=7.4.2",
    "python-docx>=1.1.0",
    "Pillow>=10.2.0",
    "pypdf>=3.0.0",
    "pyodbc>=5.0.0",
    "dnspython"
]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[deploy.dependencies.apt]
packages = ["unixodbc", "unixodbc-dev", "tdsodbc"]

[tool.bench.frappe-dependencies]
frappe = ">=15,<18"
payments = ">=0.0.1"
[tool.bench.dev-dependencies]
# package_name = "~=1.1.0"
 
[tool.ruff]
line-length = 110
target-version = "py312"
 
[tool.ruff.lint]
select = ["F", "E", "W", "I", "UP", "B", "RUF"]
ignore = [
    "B017",
    "B018",
    "B023",
    "B904",
    "E101",
    "E402",
    "E501",
    "E741",
    "F401",
    "F403",
    "F405",
    "F722",
    "W191",
]
typing-modules = ["frappe.types.DF"]
 
[tool.ruff.format]
quote-style = "double"
indent-style = "tab"
docstring-code-format = true

